CREATE OR REPLACE WAREHOUSE ANALYTICS_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE DATABASE CUSTOMER_REVENUE_ANALYTICS;

CREATE OR REPLACE SCHEMA CUSTOMER_REVENUE_ANALYTICS.RAW;
CREATE OR REPLACE SCHEMA CUSTOMER_REVENUE_ANALYTICS.STAGING;
CREATE OR REPLACE SCHEMA CUSTOMER_REVENUE_ANALYTICS.MARTS;

USE WAREHOUSE ANALYTICS_WH;
USE DATABASE CUSTOMER_REVENUE_ANALYTICS;
